version: '3.8'

services:
  hams-api:
    build: .
    container_name: hams-api
    ports:
      - "7149:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=Hospital OPD & Appointment Management System (HAMS) -1;User=sa;Password=YourStrong!Pass123;MultipleActiveResultSets=true;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    networks:
      - hamsnet

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: hams-sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Pass123"
      ACCEPT_EULA: "Y"
    networks:
      - hamsnet

networks:
  hamsnet:
    driver: bridge
